export default () => `MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMOooON0xx0MMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMWl';'.';,:NMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMNo'.;::;'.cKMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMN;.ckOOOkxl..0WKd:,,cOWMMMM
MMMMMMMMMMMMMMMMMMMMMMMO.'kOOOOkkxc.''.';::'.OMMMM
MMMMMMMMMMMMMMMWXOxl:;,'..:xOOOkxl..,:cccc:..0MMMM
MMMMMMMMMMMMXx:'.,;clooddc'.';;,..,olcccc;..kWMMMM
MMMMMMMMMMWo..,:cloxxxxxxxxdllclodxxxol:'.lXMMMMMM
MMMMMMMMMMx.':,,;ccoxxxxxxxxxxxxxxxxxxx;.dMMMMMMMM
MMMMMMMMMMc.;,...;clxxxxxxxxxc'..;dxxxxl.,0MMMMMMM
MMMMMMMMMWo.,c'.,ccoxxxxxxxxd;...;dxxxxxo'.dWMMMMM
MMMMMMMNx;...:;..:cldxxxxxxxxxddxxxxxxxxxd;.cWMMMM
MMMMMKc.'cdl..:;',ccoxxxxxxxxxxxxxxxxxxxxxd,.lWMMM
MMMWd.'lxxxxl'.';:ccdxxxxxxxxxxxxxxxxxxxxxxo..OMMM
MMWo.cdxxxxxxdl;,...'''',cxxxxxxxxxxxxxxxxxx;.:WMM
MMx.cxxxxxxxxxxxxxdddooodxxxxxxxxxxxxxxxxxxxc.,WMM
MX''dxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxc.:MMM
M0.;xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx:.xMMM
M0.,xxxxxxxxxxdoodxxxxxxxxxxxxxxxxxxxxxxxxxd''XMMM
MW;.lxxxxxxxxxxdoodxxxxxxxxxxxxxxxxxxxxxxxx:.xMMMM
MMN:.:xxxxxxxxxxdooxxxxxxxxoodxxdc;cxxxxxd;.dWMMMM
MMMWd.'oxxxxxxxxd::ldxxxxxx:..;c..;dxxxd:.'OMMMMMM
MMMMMKc.'coxxxxxl,'..;xxxxdlc;..':ccol;.,dNMMMMMMM
MMMMMMMNkc'',:c:;;;'..;::c:,,'......':o0WMMMMMMMMM
MMMMMMMMMMWXOdoccccoOOxdoolodx0NNXXNWMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
`;
